# -*- coding: utf-8 -*-
from __future__ import annotations

"""
build_demo.py
————————
PDF
 │
 ▼
Doc2X
 │
 ▼
Markdown
 │
 ▼
clean_md.py
 │
 ▼
cleaned Markdown
 │
 ▼
md_json.py
 │
 ▼
structured JSON
 │
 ▼
json_split.py
 │
 ├── paper_graph.json
 └── retrieval_docs.jsonl
 │
 ▼
metadata_processor.py
 │
 ▼
metadata_node.json
 │
 ▼
merge_metadata_to_graph.py
 │
 ▼
enriched paper_graph.json
 │
 ▼
embedding_json.py
 │
 ▼
FAISS indexes
=============

One-command builder for a single-document MatSci-RAG demonstration database.

The script orchestrates the repository modules without duplicating their logic:

PDF (optional)
  -> Doc2X Markdown
  -> clean_md.py
  -> md_json.py
  -> json_split.py
  -> metadata_processor.py
  -> merge_metadata_to_graph.py
  -> embedding_json.py

The default workspace is ``<input_stem>_matsci_rag_demo`` next to the input file.
For a PDF input, the source PDF is copied into ``source/`` so the complete public
example can keep the original and all generated intermediate artifacts together.

Example
-------
python build_demo.py \
    --input test.pdf \
    --workspace examples/test_case \
    --doc2x_env .env \
    --llm_env .env \
    --embedding_model BAAI/bge-large-en-v1.5 \
    --rerank_model BAAI/bge-reranker-large \
    --device cuda

Output layout
-------------
examples/test_case/
├── source/
│   └── test.pdf
├── doc2x_output/
│   └── test/
│       ├── test.md
│       └── images/
├── intermediate/
│   ├── test.cleaned.md
│   └── test.json
├── output/
│   ├── paper_graph.json
│   ├── retrieval_docs.jsonl
│   ├── metadata_node.json
│   ├── metadata_structured.json
│   ├── metadata_merge_report.json
│   └── faiss_section_indexes/
└── build_demo_summary.json

Notes
-----
- ``--input`` may also be a Markdown file. In that case Doc2X is skipped.
- Metadata enrichment and FAISS indexing are enabled by default but can be skipped
  independently for preprocessing-only tests.
- This script does not run QA generation; it builds the database consumed by
  ``main_pipeline.py`` / ``matsci_rag_notebook.py``.
"""

import argparse
import json
import shutil
import sys
import time
from pathlib import Path
from typing import Any, Dict, Optional


DEFAULT_SPACY_MODEL = "en_core_sci_sm"
DEFAULT_EMBEDDING_MODEL = "BAAI/bge-large-en-v1.5"
DEFAULT_RERANK_MODEL = "BAAI/bge-reranker-large"
DEFAULT_METADATA_MODEL = "glm-4-plus"
DEFAULT_MAX_CHUNK_TOKENS = 480
DEFAULT_CHUNK_OVERLAP = 1


# ============================================================
# 0. Helpers
# ============================================================

def _now() -> str:
    return time.strftime("%Y-%m-%d %H:%M:%S")


def write_json(path: str | Path, data: Any) -> None:
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")


def _strip_processing_suffixes(stem: str) -> str:
    for suffix in (".cleaned", "_cleaned", "-cleaned"):
        if stem.lower().endswith(suffix):
            return stem[: -len(suffix)]
    return stem


def infer_doc_id(input_path: str | Path) -> str:
    return _strip_processing_suffixes(Path(input_path).stem) or "document"


def default_workspace(input_path: str | Path) -> Path:
    p = Path(input_path)
    return p.parent / f"{infer_doc_id(p)}_matsci_rag_demo"


#def copy_source_file(input_path: Path, source_dir: Path) -> Path:
#    source_dir.mkdir(parents=True, exist_ok=True)
#    target = source_dir / input_path.name
#    if input_path.resolve() != target.resolve():
#        shutil.copy2(input_path, target)
#    return target

def copy_source_file(input_path: Path, source_dir: Path) -> Path:
    """
    Copy the source file into workspace/source.

    For Markdown input, also copy a sibling `images/` directory when present,
    so the demo workspace remains self-contained and local figure references
    can still be resolved after the Markdown file is moved.
    """
    source_dir.mkdir(parents=True, exist_ok=True)

    target = source_dir / input_path.name

    if input_path.resolve() != target.resolve():
        shutil.copy2(input_path, target)

    # Markdown input may rely on a sibling images/ directory generated by Doc2X.
    if input_path.suffix.lower() == ".md":
        source_images = input_path.parent / "images"
        target_images = source_dir / "images"

        if source_images.exists() and source_images.is_dir():
            if target_images.exists():
                shutil.rmtree(target_images)

            shutil.copytree(source_images, target_images)

            print(f"[ASSETS] Copied images directory:")
            print(f"         {source_images}")
            print(f"      -> {target_images}")
        else:
            print(
                f"[WARN] Markdown input has no sibling images directory: "
                f"{source_images}"
            )

    return target

def stage_header(number: int, title: str) -> None:
    print("\n" + "=" * 88)
    print(f"STEP {number}: {title}")
    print("=" * 88)


# ============================================================
# 1. Individual stages
# ============================================================

def run_pdf_stage(
    pdf_path: Path,
    doc2x_output_dir: Path,
    env_file: Optional[str],
    debug: bool,
    keep_zip: bool,
    force: bool,
    output_format: str,
) -> Path:
    from pdf_to_md import pdf_to_md

    return pdf_to_md(
        pdf_file=pdf_path,
        output_dir=doc2x_output_dir,
        env_file_path=env_file,
        debug=debug,
        remove_zip=not keep_zip,
        output_format=output_format,
        force=force,
    )


def run_clean_stage(markdown_path: Path, cleaned_path: Path) -> Path:
    from clean_md import clean_markdown_file

    return clean_markdown_file(
        input_path=markdown_path,
        output_path=cleaned_path,
        rebase_assets=True,
    )


def run_md_json_stage(
    cleaned_path: Path,
    json_path: Path,
    doc_id: str,
    source_file: str,
) -> Path:
    from md_json import convert_markdown_file

    return convert_markdown_file(
        input_path=cleaned_path,
        output_path=json_path,
        doc_id=doc_id,
        source_file=source_file,
    )


def run_graph_stage(
    json_path: Path,
    output_dir: Path,
    doc_id: str,
    spacy_model: str,
    tokenizer_model: str,
    max_chunk_tokens: int,
    chunk_overlap: int,
) -> Dict[str, Path]:
    from json_split import (
        build_evidence_graph_from_md_json,
        read_json,
        write_json as write_graph_json,
        write_jsonl,
    )

    data = read_json(str(json_path))
    source_file = str(data.get("source_file") or json_path.name)

    graph, retrieval_docs = build_evidence_graph_from_md_json(
        data=data,
        source_file=source_file,
        doc_id=doc_id,
        spacy_model=spacy_model,
        tokenizer_model=tokenizer_model,
        max_chunk_tokens=max_chunk_tokens,
        chunk_overlap=chunk_overlap,
    )

    output_dir.mkdir(parents=True, exist_ok=True)
    graph_path = output_dir / "paper_graph.json"
    retrieval_path = output_dir / "retrieval_docs.jsonl"
    write_graph_json(str(graph_path), graph)
    write_jsonl(str(retrieval_path), retrieval_docs)

    print("[OK] Evidence graph built")
    print(f"[GRAPH]     {graph_path}")
    print(f"[RETRIEVAL] {retrieval_path}")
    print("[STATS]")
    print(json.dumps(graph.get("stats", {}), ensure_ascii=False, indent=2))

    return {
        "graph": graph_path,
        "retrieval_docs": retrieval_path,
    }


def run_metadata_stage(
    json_path: Path,
    output_dir: Path,
    doc_id: str,
    env_file: Optional[str],
    model_name: str,
    tokenizer_model: str,
    max_embedding_tokens: int,
    debug: bool,
    force: bool,
) -> Dict[str, Any]:
    from metadata_processor import process_metadata

    return process_metadata(
        input_json_path=str(json_path),
        output_dir=str(output_dir),
        env_file_path=env_file,
        model_name=model_name,
        tokenizer_model=tokenizer_model,
        max_embedding_tokens=max_embedding_tokens,
        doc_id=doc_id,
        debug=debug,
        force=force,
    )


def run_merge_stage(
    graph_path: Path,
    metadata_node_path: Path,
    report_path: Path,
) -> Dict[str, Any]:
    from merge_metadata_to_graph import (
        merge_metadata_node_into_graph,
        read_json,
        write_json as write_merge_json,
    )

    graph_data = read_json(graph_path)
    metadata_node = read_json(metadata_node_path)

    merged_graph, report = merge_metadata_node_into_graph(
        graph_data=graph_data,
        metadata_node=metadata_node,
        replace_existing=True,
        update_enrichment_status=True,
        allow_source_file_mismatch=False,
    )

    write_merge_json(graph_path, merged_graph)
    write_merge_json(report_path, report)

    print("[OK] metadata_structured merged into paper_graph.json")
    print(f"[REPORT] {report_path}")
    return report


def run_embedding_stage(
    output_dir: Path,
    embedding_model: str,
    device: str,
    verbose: bool,
) -> Dict[str, Any]:
    from embedding_json import build_indexes

    return build_indexes(
        output_dir=str(output_dir),
        model_name=embedding_model,
        device=device,
        retrieval_jsonl=None,
        graph_json=None,
        index_dir=None,
        trust_remote_code=True,
        normalize_embeddings=True,
        verbose=verbose,
    )


# ============================================================
# 2. Orchestration
# ============================================================

def build_demo(
    input_file: str | Path,
    workspace: Optional[str | Path] = None,
    doc_id: Optional[str] = None,
    source_file: Optional[str] = None,
    copy_source: bool = True,
    doc2x_env: Optional[str] = None,
    doc2x_debug: bool = False,
    doc2x_keep_zip: bool = False,
    doc2x_force: bool = False,
    doc2x_output_format: str = "md_dollar",
    llm_env: Optional[str] = None,
    metadata_model: str = DEFAULT_METADATA_MODEL,
    metadata_debug: bool = False,
    metadata_force: bool = False,
    skip_metadata: bool = False,
    skip_embedding: bool = False,
    spacy_model: str = DEFAULT_SPACY_MODEL,
    tokenizer_model: Optional[str] = None,
    embedding_model: str = DEFAULT_EMBEDDING_MODEL,
    rerank_model: str = DEFAULT_RERANK_MODEL,
    device: str = "auto",
    max_chunk_tokens: int = DEFAULT_MAX_CHUNK_TOKENS,
    chunk_overlap: int = DEFAULT_CHUNK_OVERLAP,
    embedding_verbose: bool = False,
) -> Dict[str, Any]:
    input_path = Path(input_file).resolve()
    if not input_path.exists():
        raise FileNotFoundError(f"Input file not found: {input_path}")
    if input_path.suffix.lower() not in {".pdf", ".md"}:
        raise ValueError("--input must be a .pdf or .md file")

    resolved_doc_id = (doc_id or "").strip() or infer_doc_id(input_path)
    workspace_path = Path(workspace).resolve() if workspace else default_workspace(input_path).resolve()
    source_dir = workspace_path / "source"
    doc2x_output_dir = workspace_path / "doc2x_output"
    intermediate_dir = workspace_path / "intermediate"
    output_dir = workspace_path / "output"

    for d in (workspace_path, source_dir, intermediate_dir, output_dir):
        d.mkdir(parents=True, exist_ok=True)

    tokenizer_model = tokenizer_model or embedding_model

    # The reranker is not needed to build FAISS indexes, but is captured in the
    # build summary because the same workspace is intended for main_pipeline.py.
    summary: Dict[str, Any] = {
        "schema_version": "1.0-demo-build",
        "started_at": _now(),
        "input": str(input_path),
        "workspace": str(workspace_path),
        "doc_id": resolved_doc_id,
        "configuration": {
            "spacy_model": spacy_model,
            "tokenizer_model": tokenizer_model,
            "embedding_model": embedding_model,
            "rerank_model": rerank_model,
            "device": device,
            "max_chunk_tokens": max_chunk_tokens,
            "chunk_overlap_sentences": chunk_overlap,
            "metadata_model": metadata_model,
            "metadata_enabled": not skip_metadata,
            "embedding_enabled": not skip_embedding,
            "doc2x_output_format": doc2x_output_format,
        },
        "steps": {},
        "outputs": {},
    }

    # --------------------------------------------------------
    # Source + PDF/Markdown input
    # --------------------------------------------------------
    if copy_source:
        working_source = copy_source_file(input_path, source_dir)
    else:
        working_source = input_path

    summary["outputs"]["source"] = str(working_source)

    if input_path.suffix.lower() == ".pdf":
        stage_header(1, "PDF -> Markdown (Doc2X)")
        markdown_path = run_pdf_stage(
            pdf_path=working_source,
            doc2x_output_dir=doc2x_output_dir,
            env_file=doc2x_env,
            debug=doc2x_debug,
            keep_zip=doc2x_keep_zip,
            force=doc2x_force,
            output_format=doc2x_output_format,
        )
        source_label = Path(source_file).name if source_file else input_path.name
        summary["steps"]["pdf_to_md"] = "completed"
    else:
        stage_header(1, "Markdown input (Doc2X stage skipped)")
        markdown_path = working_source
        source_label = Path(source_file).name if source_file else input_path.name
        summary["steps"]["pdf_to_md"] = "skipped_markdown_input"
        print(f"[MD] {markdown_path}")

    summary["outputs"]["markdown"] = str(markdown_path)
    summary["source_file"] = source_label

    # --------------------------------------------------------
    # Clean Markdown
    # --------------------------------------------------------
    stage_header(2, "Markdown normalization")
    cleaned_path = intermediate_dir / f"{resolved_doc_id}.cleaned.md"
    run_clean_stage(markdown_path, cleaned_path)
    summary["steps"]["clean_md"] = "completed"
    summary["outputs"]["cleaned_markdown"] = str(cleaned_path)
    print(f"[OK] {cleaned_path}")

    # --------------------------------------------------------
    # Markdown -> structured JSON
    # --------------------------------------------------------
    stage_header(3, "Markdown -> structured JSON")
    json_path = intermediate_dir / f"{resolved_doc_id}.json"
    run_md_json_stage(
        cleaned_path=cleaned_path,
        json_path=json_path,
        doc_id=resolved_doc_id,
        source_file=source_label,
    )
    summary["steps"]["md_json"] = "completed"
    summary["outputs"]["structured_json"] = str(json_path)
    print(f"[OK] {json_path}")

    # --------------------------------------------------------
    # JSON -> graph + retrieval docs
    # --------------------------------------------------------
    stage_header(4, "Structured JSON -> evidence graph")
    graph_outputs = run_graph_stage(
        json_path=json_path,
        output_dir=output_dir,
        doc_id=resolved_doc_id,
        spacy_model=spacy_model,
        tokenizer_model=tokenizer_model,
        max_chunk_tokens=max_chunk_tokens,
        chunk_overlap=chunk_overlap,
    )
    summary["steps"]["json_split"] = "completed"
    summary["outputs"].update({k: str(v) for k, v in graph_outputs.items()})

    # --------------------------------------------------------
    # Metadata enrichment + merge
    # --------------------------------------------------------
    if skip_metadata:
        stage_header(5, "Metadata enrichment skipped")
        summary["steps"]["metadata_processor"] = "skipped"
        summary["steps"]["merge_metadata"] = "skipped"
    else:
        stage_header(5, "Structured metadata enrichment")
        metadata_summary = run_metadata_stage(
            json_path=json_path,
            output_dir=output_dir,
            doc_id=resolved_doc_id,
            env_file=llm_env,
            model_name=metadata_model,
            tokenizer_model=tokenizer_model,
            max_embedding_tokens=max_chunk_tokens,
            debug=metadata_debug,
            force=metadata_force,
        )
        summary["steps"]["metadata_processor"] = "completed"
        summary["metadata"] = metadata_summary

        metadata_node_path = output_dir / "metadata_node.json"
        merge_report_path = output_dir / "metadata_merge_report.json"

        stage_header(6, "Merge metadata into evidence graph")
        merge_report = run_merge_stage(
            graph_path=graph_outputs["graph"],
            metadata_node_path=metadata_node_path,
            report_path=merge_report_path,
        )
        summary["steps"]["merge_metadata"] = "completed"
        summary["metadata_merge"] = merge_report
        summary["outputs"]["metadata_node"] = str(metadata_node_path)
        summary["outputs"]["metadata_merge_report"] = str(merge_report_path)

    # --------------------------------------------------------
    # Embedding / FAISS
    # --------------------------------------------------------
    if skip_embedding:
        stage_header(7, "Embedding / FAISS indexing skipped")
        summary["steps"]["embedding_json"] = "skipped"
    else:
        stage_header(7, "Embedding + FAISS indexing")
        manifest = run_embedding_stage(
            output_dir=output_dir,
            embedding_model=embedding_model,
            device=device,
            verbose=embedding_verbose,
        )
        summary["steps"]["embedding_json"] = "completed"
        summary["faiss_manifest"] = manifest
        summary["outputs"]["faiss_index_dir"] = str(output_dir / "faiss_section_indexes")

    summary["completed_at"] = _now()
    summary_path = workspace_path / "build_demo_summary.json"
    summary["outputs"]["build_summary"] = str(summary_path)
    write_json(summary_path, summary)

    print("\n" + "=" * 88)
    print("DEMO DATABASE BUILD COMPLETED")
    print("=" * 88)
    print(f"[WORKSPACE] {workspace_path}")
    print(f"[GRAPH]     {output_dir / 'paper_graph.json'}")
    print(f"[RETRIEVAL] {output_dir / 'retrieval_docs.jsonl'}")
    if not skip_embedding:
        print(f"[FAISS]     {output_dir / 'faiss_section_indexes'}")
    print(f"[SUMMARY]   {summary_path}")

    return summary


# ============================================================
# 3. CLI
# ============================================================

def main() -> None:
    parser = argparse.ArgumentParser(
        description=(
            "Build a complete single-document MatSci-RAG demo database from PDF "
            "or Markdown using the repository processing pipeline."
        )
    )
    parser.add_argument("--input", required=True, help="Input PDF or Doc2X-style Markdown")
    parser.add_argument(
        "--workspace",
        default=None,
        help="Workspace root; defaults to <input_stem>_matsci_rag_demo beside input",
    )
    parser.add_argument("--doc_id", default=None, help="Optional stable document ID")
    parser.add_argument(
        "--source_file",
        default=None,
        help="Optional provenance label, normally the original PDF filename",
    )
    parser.add_argument(
        "--no_copy_source",
        action="store_true",
        help="Do not copy the input file into workspace/source",
    )

    # Doc2X
    parser.add_argument("--doc2x_env", default=None, help="Env file for DOC2X_API_KEY/API_KEY")
    parser.add_argument("--doc2x_debug", action="store_true")
    parser.add_argument("--keep_doc2x_zip", action="store_true")
    parser.add_argument("--force_doc2x", action="store_true")
    parser.add_argument("--doc2x_output_format", default="md_dollar")

    # Metadata LLM
    parser.add_argument("--llm_env", default=None, help="Env file for metadata-structuring LLM")
    parser.add_argument("--metadata_model", default=DEFAULT_METADATA_MODEL)
    parser.add_argument("--metadata_debug", action="store_true")
    parser.add_argument("--force_metadata", action="store_true")
    parser.add_argument("--skip_metadata", action="store_true")

    # Chunking / embedding
    parser.add_argument("--spacy_model", default=DEFAULT_SPACY_MODEL)
    parser.add_argument(
        "--tokenizer_model",
        default=None,
        help="Tokenizer name/path; defaults to --embedding_model",
    )
    parser.add_argument("--embedding_model", default=DEFAULT_EMBEDDING_MODEL)
    parser.add_argument(
        "--rerank_model",
        default=DEFAULT_RERANK_MODEL,
        help="Recorded for downstream main_pipeline configuration; not loaded during build",
    )
    parser.add_argument("--device", default="auto")
    parser.add_argument("--max_chunk_tokens", type=int, default=DEFAULT_MAX_CHUNK_TOKENS)
    parser.add_argument("--chunk_overlap", type=int, default=DEFAULT_CHUNK_OVERLAP)
    parser.add_argument("--skip_embedding", action="store_true")
    parser.add_argument("--embedding_verbose", action="store_true")

    args = parser.parse_args()

    build_demo(
        input_file=args.input,
        workspace=args.workspace,
        doc_id=args.doc_id,
        source_file=args.source_file,
        copy_source=not args.no_copy_source,
        doc2x_env=args.doc2x_env,
        doc2x_debug=args.doc2x_debug,
        doc2x_keep_zip=args.keep_doc2x_zip,
        doc2x_force=args.force_doc2x,
        doc2x_output_format=args.doc2x_output_format,
        llm_env=args.llm_env,
        metadata_model=args.metadata_model,
        metadata_debug=args.metadata_debug,
        metadata_force=args.force_metadata,
        skip_metadata=args.skip_metadata,
        skip_embedding=args.skip_embedding,
        spacy_model=args.spacy_model,
        tokenizer_model=args.tokenizer_model,
        embedding_model=args.embedding_model,
        rerank_model=args.rerank_model,
        device=args.device,
        max_chunk_tokens=args.max_chunk_tokens,
        chunk_overlap=args.chunk_overlap,
        embedding_verbose=args.embedding_verbose,
    )


if __name__ == "__main__":
    main()
